// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdgi7dylvDQhCKa4s7ufN8s-9NjQJDtLY',
    appId: '1:53296546414:web:d8ca596b8909f784fd9c7f',
    messagingSenderId: '53296546414',
    projectId: 'hangman-14eef',
    authDomain: 'hangman-14eef.firebaseapp.com',
    databaseURL: 'https://hangman-14eef-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hangman-14eef.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgTfIWLlLuxlF9nnNra0rs7Hl1pkuDzvU',
    appId: '1:53296546414:android:c843f6e5d490a06afd9c7f',
    messagingSenderId: '53296546414',
    projectId: 'hangman-14eef',
    databaseURL: 'https://hangman-14eef-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hangman-14eef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbiqosMiHXKPkDwbo_B2VWAY6MT34GmDQ',
    appId: '1:53296546414:ios:310f1be3b9146056fd9c7f',
    messagingSenderId: '53296546414',
    projectId: 'hangman-14eef',
    databaseURL: 'https://hangman-14eef-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hangman-14eef.appspot.com',
    iosClientId: '53296546414-jbgavqfk8dil9bkh3t2dlco3pd2rtm6i.apps.googleusercontent.com',
    iosBundleId: 'hangman.mitimsin.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbiqosMiHXKPkDwbo_B2VWAY6MT34GmDQ',
    appId: '1:53296546414:ios:bff5f2e9076af5e7fd9c7f',
    messagingSenderId: '53296546414',
    projectId: 'hangman-14eef',
    databaseURL: 'https://hangman-14eef-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hangman-14eef.appspot.com',
    iosClientId: '53296546414-f9blkj2gv7kfr2r1gusg33cnuiufc01i.apps.googleusercontent.com',
    iosBundleId: 'com.example.hangman',
  );
}
